version: '3.8'

services:
  bedrock:
    build: .
    container_name: bedrock
    ports:
      - '19132:19132/udp'
    environment:
      EULA: 'TRUE'
      LEVEL_NAME: 'Home'
      SERVER_NAME: 'Home MC Server'
      MAX_PLAYERS: '10'
    volumes:
      - ./data:/data
    restart: unless-stopped
    stdin_open: true
    tty: true
